Updated the ssm document

diff --git a/IAC/Cloudformation/Infrastructure/Nested-Stacks/Initiate-Account/CloudAdminSudoersFile.yaml b/IAC/Cloudformation/Infrastructure/Nested-Stacks/Initiate-Account/CloudAdminSudoersFile.yaml
--- a/IAC/Cloudformation/Infrastructure/Nested-Stacks/Initiate-Account/CloudAdminSudoersFile.yaml
+++ b/IAC/Cloudformation/Infrastructure/Nested-Stacks/Initiate-Account/CloudAdminSudoersFile.yaml
@@ -16,6 +16,21 @@ parameters:
       description: The Cloudadmins group to be added to the sudoers file
       type: String
       default: "Cloudadmins@kahbrigthllc.com"
+
+    pDomain:
+      description: The doamin to be joined by the instance 
+      type: String
+      default: "kahbrigthllc.com"
+    
+    pJoinAccount:
+      description: The account that has domain priviliges 
+      type: StringList
+      default: ["{{ssm:/standard/pDomainJoinAccount}}"]
+
+    pJoinPassword:
+      description: The password used for instance domain join 
+      type: StringList
+      default: ["{{ssm://standard/pDomainJoinPassword}}"]
 mainSteps:
           - action: aws:runShellScript
             name: InstallClouAdminGroup
@@ -24,45 +39,66 @@ mainSteps:
             inputs:
               runCommand:
                   - |
-                        #!/bin/bash -xe
-                          ##########################################
-                          #  DOMAIN GROUP ADDING TO SUDOERS FILE  #
-                          ##########################################
-                          ParamSSHDConfigFilePath='{{ pSSHDConfigFilePath }}' 
-                          ParamSudoersFilePath='{{ pSudoersFilePath }}'  
-                          ParamCloudAdminsGroup='{{ pCloudAdminsGroup }}'                       
-                          
-                          # Enable PasswordAuthentication if not already enabled
-                          if sudo grep -q "^PasswordAuthentication yes" "$ParamSSHDConfigFilePath"; then
-                              echo "PasswordAuthentication is already set to yes."
-                          else
-                              echo "Setting PasswordAuthentication to yes..."
-                              sudo sed -i 's/^#PasswordAuthentication no/PasswordAuthentication yes/' "$ParamSSHDConfigFilePath"
-                              sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' "$ParamSSHDConfigFilePath"
-                              echo "PasswordAuthentication has been set to yes."
-                              # Restart SSH service to apply changes
-                              sudo systemctl restart sshd
-                          fi
+                       #!/bin/bash -xe
+                        ##########################################
+                        #  DOMAIN GROUP ADDING TO SUDOERS FILE  #
+                        ##########################################
+                        # Parameters
+                        ParamSSHDConfigFilePath='{{ pSSHDConfigFilePath }}' 
+                        ParamSudoersFilePath='{{ pSudoersFilePath }}'  
+                        ParamCloudAdminsGroup='{{ pCloudAdminsGroup }}'
+                        ParamDomain='{{ pDomain }}'
+                        ParamJoinAccount='{{ pJoinAccount }}'
+                        ParamJoinPassword='{{ pJoinPassword }}'
 
-                          # Check if the Cloudadmins group is already in the sudoers file
-                          if sudo grep -q "%$ParamCloudAdminsGroup" "$ParamSudoersFilePath"; then
-                              echo "The group $ParamCloudAdminsGroup is already in the sudoers file."
-                          else
-                              echo "Adding $ParamCloudAdminsGroup to the sudoers file with NOPASSWD..."
-                              # Add the Cloudadmins group to the sudoers file with NOPASSWD
-                              echo "%$ParamCloudAdminsGroup ALL=(ALL) NOPASSWD:ALL" | sudo tee -a "$ParamSudoersFilePath" > /dev/null
-                              # Verify the sudoers file
-                              if sudo visudo -cf "$ParamSudoersFilePath"; then
-                                  echo "Sudoers file is valid."
-                              else
-                                  echo "Sudoers file is invalid, please check."
-                                  exit 1
-                              fi
-                          fi
+                        ###############################################
+                        #   TAILORED FUNCTION #
+                        ###############################################
+                        # Step 1: Update the system and install necessary packages
+                        echo "Updating system and installing required packages..."
+                        sudo yum -y update
+                        sudo yum install -y samba-common-tools realmd oddjob sssd adcli krb5-workstation
 
+                        # Step 2: Automate the domain join process
+                        echo "Joining the domain $ParamDomain..."
 
+                        # Pass the password to the realm join command securely
+                        echo "$ParamJoinPassword" | sudo realm join -U "$ParamJoinAccount" "$ParamDomain" --verbose --install=sssd --install=krb5-workstation --install=adcli --install=samba-common-tools --install=realmd
 
+                        # Verify domain join
+                        if [ $? -eq 0 ]; then
+                            echo "Successfully joined the domain $ParamDomain"
+                        else
+                            echo "Failed to join the domain $ParamDomain"
+                            exit 1
+                        fi
 
+                        # Step 3: Enable PasswordAuthentication if not already enabled
+                        if sudo grep -q "^PasswordAuthentication yes" "$ParamSSHDConfigFilePath"; then
+                            echo "PasswordAuthentication is already set to yes."
+                        else
+                            echo "Setting PasswordAuthentication to yes..."
+                            sudo sed -i 's/^#PasswordAuthentication no/PasswordAuthentication yes/' "$ParamSSHDConfigFilePath"
+                            sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' "$ParamSSHDConfigFilePath"
+                            echo "PasswordAuthentication has been set to yes."
+                            # Restart SSH service to apply changes
+                            sudo systemctl restart sshd
+                        fi
 
+                        # Step 4: Check if the Cloudadmins group is already in the sudoers file
+                        if sudo grep -q "%$ParamCloudAdminsGroup" "$ParamSudoersFilePath"; then
+                            echo "The group $ParamCloudAdminsGroup is already in the sudoers file."
+                        else
+                            echo "Adding $ParamCloudAdminsGroup to the sudoers file with NOPASSWD..."
+                            # Add the Cloudadmins group to the sudoers file with NOPASSWD
+                            echo "%$ParamCloudAdminsGroup ALL=(ALL) NOPASSWD:ALL" | sudo tee -a "$ParamSudoersFilePath" > /dev/null
+                            # Verify the sudoers file
+                            if sudo visudo -cf "$ParamSudoersFilePath"; then
+                                echo "Sudoers file is valid."
+                            else
+                                echo "Sudoers file is invalid, please check."
+                                exit 1
+                            fi
+                        fi
 
-
+                        echo "SSM document execution complete!"
